import { parse, stringify } from 'yaml';

const FRONTMATTER = /^---\s*\r?\n([\s\S]*?)\r?\n---\s*(?:\r?\n|$)/;

export function parseMarkdown(raw, file = '<content>') {
  const normalized = raw.replace(/^\uFEFF/, '');
  const match = normalized.match(FRONTMATTER);
  if (!match) throw new Error(`${file}: missing YAML front matter.`);

  let data;
  try {
    data = parse(match[1]);
  } catch (error) {
    throw new Error(`${file}: invalid YAML front matter: ${error.message}`);
  }
  if (!data || typeof data !== 'object' || Array.isArray(data)) {
    throw new Error(`${file}: front matter must be a YAML object.`);
  }

  return {
    data,
    body: normalized.slice(match[0].length),
    raw: normalized,
    frontmatterLength: match[0].length,
  };
}

export function serializeMarkdown(data, body, generatedComment = true) {
  const yaml = stringify(data, { lineWidth: 0 }).trimEnd();
  const marker = generatedComment
    ? '<!-- GENERATED FROM THE PRIVATE KNOWLEDGE BASE. DO NOT EDIT THIS FILE. -->\n\n'
    : '';
  return `---\n${yaml}\n---\n\n${marker}${body.trim()}\n`;
}
